---
title: "Completude"
output: 
  prettydoc::html_pretty:
    theme: cayman
    css: './prettydoc-cayman.css'
editor_options: 
  chunk_output_type: inline
---

```{r setup, echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(hrbrthemes)
library(reactable)
theme_set(theme_ipsum_rc())
# https://coolors.co/083d77-ebebd3-da4167-f4d35e-f78764

knitr::opts_chunk$set(tidy = FALSE, 
                      echo = FALSE,
                      fig.height = 10,
                      fig.width = 8)
set.seed(1014)
options(digits = 2, scipen = 999)
```

```{r}
incomes = read_csv(
  here::here("dados/ready/incomes-all.csv"),
  col_types = cols(
    aid = col_character(),
    month = col_integer(),
    year = col_integer(),
    date = col_date(),
    reg = col_character(),
    name = col_character(),
    role = col_character(),
    type = col_character(),
    workplace = col_character(),
    active = col_logical(),
    .default = col_double()
  )
)

incomes = incomes %>% 
  mutate(aid_class = case_when(
    str_starts(aid, "mp") ~ "MP", 
    str_starts(aid, "tj") ~ "TJ", 
    str_starts(aid, "tre") ~ "TRE", 
    str_starts(aid, "trt") ~ "TRT", 
    TRUE ~ NA_character_
  )) 
# %>% 
#   filter(!(aid_class %in% c("TRE", "TRT")))

```

## Órgãos cobertos

```{r}
incomes %>% 
  summarise(
    tipos_orgao = n_distinct(aid_class),
    orgaos = n_distinct(aid), 
    anos = n_distinct(year), 
    meses = n_distinct(month, year)
  ) %>% 
  reactable() 
```

### De quando a quando por órgão

```{r}
incomes %>%
  group_by(aid_class, aid) %>%
  summarise(
    data_inicial = min(date),
    data_final = max(date),
    anos = n_distinct(year),
    meses = n_distinct(month, year),
    .groups = "drop"
  ) %>%
  reactable(striped = T, searchable = T) 
```

## Preenchimento mês a mês

O Preenchimento Relativo de um órgão emum mês é o número de registros de um mês dividido pelo maior número de registros do órgão.

```{r}
incomes %>% 
  group_by(aid_class) %>% 
  summarise(orgaos = n_distinct(aid)) %>% 
  reactable(striped = T)
```

```{r}
contagens = incomes %>% 
  group_by(aid_class, aid, date) %>% 
  summarise(registros = n(), .groups = "drop") %>% 
  complete(nesting(aid_class, aid), date, fill = list(registros = NA)) %>% 
  group_by(aid) %>% 
  mutate(relativo = registros/max(registros, na.rm = T)) %>% 
  ungroup()
```

```{r}
contagens %>% 
  summarise(
    Total = n(),
    `Pouco preenchidos`= sum(relativo < .5, na.rm = T), 
    `Pouco prop` = `Pouco preenchidos` / n(), 
    `Faltantes`  = sum(is.na(relativo), na.rm = T), 
    `Faltantes prop` = Faltantes / n()) %>% 
  reactable(striped = T)
```



```{r fig.height=8, fig.width=9}
contagens %>%
  mutate(relativo_temp = replace_na(relativo, 0),
         relativo = pmax(relativo, .5)) %>%
  ggplot(aes(
    y = reorder(aid, relativo_temp, sd),
    x = date,
    fill = relativo
  )) +
  facet_grid(reorder(aid_class, relativo_temp, mean) ~ ., scales = "free") +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", na.value = "gray80") +
  labs(
    title = "Registros recuperados",
    subtitle = "Quão preenchido está cada mês comparado ao maior. Cinza é faltante.",
    y = "",
    fill = "Preenchimento relativo"
  )

ggsave("preenchimentos.png", height = 8, width = 9, dpi = 100)
```

```{r}
# incomes %>% 
#   filter(aid == "tjsp", year == 2018, month == 1)
```


```{r fig.height=15, fig.width=8}
contagens %>% 
  mutate(relativo = replace_na(relativo, 0)) %>% 
  ggplot(aes(x = date, y = relativo, color = relativo)) + 
  facet_wrap(~ reorder(aid, relativo, function(x) -sd(x)), ncol = 4) + 
  # geom_line(color = "deeppink4", size = 1.1) + 
  geom_point(size = 1.5, show.legend = F) + 
  scale_color_viridis_c(option = "magma") + 
  scale_y_continuous(breaks = c(0, 1)) + 
  labs(y = "Preenchimento relativo", 
       title = "Detalhe mês a mês") 
```
Em formato de tabela buscável: 

```{r}
contagens %>% 
  mutate(relativo = round(relativo, 2)) %>% 
  reactable(striped = T, searchable = T)
```

## Valor

```{r}
totais = incomes %>% 
  group_by(aid_class, aid, date) %>% 
  summarise(total = sum(income_total), .groups = "drop") %>% 
  complete(nesting(aid_class, aid), date, fill = list(total = NA)) %>% 
  group_by(aid) %>% 
  mutate(relativo = total/max(total, na.rm = T)) 

totais %>%
  mutate(relativo_temp = replace_na(relativo, 0)) %>%
  ggplot(aes(
    y = reorder(aid, relativo_temp, sd),
    x = date,
    fill = relativo
  )) +
  facet_grid(reorder(aid_class, relativo_temp, mean) ~ ., scales = "free") +
  geom_tile() +
  scale_fill_viridis_c(option = "viridis", na.value = "gray80", direction = -1) +
  labs(
    title = "Montante reportado",
    subtitle = "Razão entre remuneração total no mês e maior mês. Cinza significa faltante.",
    y = "",
    fill = "Valor relativo\nao máximo"
  )

ggsave("montantes.png", height = 8, width = 9, dpi = 100)
```
